title: dae-cpp
description: A simple but powerful header-only C++ solver for systems of Differential-Algebraic Equations (DAE)
theme: just-the-docs

url: https://dae-cpp.github.io

# For copy button on code
enable_copy_code_button: true

aux_links:
  "dae-cpp on GitHub":
    - "https://github.com/dae-cpp/dae-cpp"
